<a href="https://colab.research.google.com/github/kanjsoni/MLpractice/blob/main/numpyprj2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arithmetic Operation

In [5]:
import numpy as np
var = np.array([1,2,3,4,5])
varAdd =np.add(var,3)
print(varAdd)

[4 5 6 7 8]


In [9]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varAdd = np.add(var1,var2)
print(varAdd)

[2 4 6 8]


In [10]:
var1 = np.array([4,6,6,8])
var2 = np.array([1,2,3,4])
varSub = np.subtract(var1,var2)
print(varSub)


[3 4 3 4]


In [11]:
var1 = np.array([4,6,6,8])
var2 = np.array([1,2,3,4])
varmul = np.multiply(var1,var2)
print(varmul)

[ 4 12 18 32]


In [12]:
var1 = np.array([4,6,6,8])
var2= np.array([1,2,3,4])
vardiv = np.divide(var1,var2)
print(vardiv)

[4. 3. 2. 2.]


In [13]:
var1 = np.array([2,5,6,6])
var2 = np.array([1,2,3,4])
varmod = np.mod(var1,var2)
print(varmod)

[0 1 0 2]


In [14]:
var1 = np.array([2,5,6,6])
var2 = np.array([1,2,3,4])
varpow = np.power(var1,var2)
print(varpow)

[   2   25  216 1296]


In [15]:
var1 = np.array([1,5,3,5])
var2 = np.array([1,2,3,4])
varrec = np.reciprocal(var1)
print(varrec)


[1 0 0 0]


2D array

In [16]:
var21 = np.array([[1,2,3,4],[2,4,5,6]])
var22 = np.array([[1,2,3,4],[2,4,5,6]])
var23 = np.add(var21,var22)
print(var23)


[[ 2  4  6  8]
 [ 4  8 10 12]]


Shape And Reshape of numpy Array

In [19]:
var31 = np.array([[1,2,3,4],[2,4,5,6]])
print(var31.shape)
var32 = np.array([1,2,3,4],ndmin=4)
print(var32)
print(var32.shape)

(2, 4)
[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [20]:
var41 = np.array([1,2,3,5])
x = var41.reshape(2,2)
print(x)

[[1 2]
 [3 5]]


Broadcasting

In [23]:
var51 = np.array([1,2,3])
print(var51.shape)
var52 = np.array([[1],[2],[3]])
print(var52)
print(var52.shape)
print(var51 + var52)


(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


Indexing