<a href="https://colab.research.google.com/github/kanjsoni/MLpractice/blob/main/numpybasic3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Indexing**

In [2]:
import numpy as np
var = np.array([4,6,4,3,5])
print(var[0])
print(var[1])


4
6


In [3]:
var1 = np.array([[9,5,7,4,3],[4,6,3,7,3]])
print(var1)
print(var1.ndim)
print(var1[0,1])
print(var1[1,3])

[[9 5 7 4 3]
 [4 6 3 7 3]]
2
5
7


Iterating numpy arrays

In [4]:
var21 = np.array([9,5,7,4,3,])
print(var21)
for i in var21:
    print(i)


[9 5 7 4 3]
9
5
7
4
3


In [6]:
var31 = np.array([[9,5,7,4,3],[4,6,3,7,3]])
print(var31)
for j in var31:
    print(j)
print()
for k in var31:
    for l in k:
        print(l)

[[9 5 7 4 3]
 [4 6 3 7 3]]
[9 5 7 4 3]
[4 6 3 7 3]

9
5
7
4
3
4
6
3
7
3


In [8]:
var41 = np.array([[[1,3,4,5],[2,5,6,8]]])
print(var41)
for m in var41:
    print(m)
for n in var41:
    for o in n:
        for p in o:
            print(p)

[[[1 3 4 5]
  [2 5 6 8]]]
[[1 3 4 5]
 [2 5 6 8]]
1
3
4
5
2
5
6
8


Copy function in numpy

In [9]:
var51 = np.array([1,4,5])
print("Original Data",var51)
copyVar = var51.copy()
print("Copied Data", copyVar)

Original Data [1 4 5]
Copied Data [1 4 5]


View Data

In [10]:
var61 = np.array([1,4,5,6])
vi = var61.view()
print("Original Data", var61)
print("Viewed Data",vi)

Original Data [1 4 5 6]
Viewed Data [1 4 5 6]
