<a href="https://colab.research.google.com/github/kanjsoni/MLpractice/blob/main/numpyBasic4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sort and filter

In [2]:
import numpy as np

var = np.array([1,3,4,6,2,7,9,4,2,6,5,3,2])
# where keyword is used to search element index
x = np.where( var == 2)
print(x)


(array([ 4,  8, 12]),)


Search Sorted Array

In [5]:
var1 = np.array([1,2,3,4,5,6,7,8,9])
x1 = np.searchsorted(var1, 5)
print(x1)
print(var1)

4
[1 2 3 4 5 6 7 8 9]


Function in Numpy array
Arithmetic Functions
-> Shuffle
-> Unique
-> Resize
-> Flatten
->Ravel

In [6]:
# Shuffle
var2 = np.array([1,2,3,4,5,6,7,8,9])

np.random.shuffle(var2)
print(var2)

[3 2 7 5 6 8 1 9 4]


In [9]:
# unique
var3 = np.array([1,2,3,4,5,6,5,3,6,8,3,9,2,1,5,9,7,0,4,0,3,2,0,5])
x = np.unique(var3, return_index=True, return_counts=True)
print(x)


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([17,  0,  1,  2,  3,  4,  5, 16,  9, 11]), array([3, 2, 3, 4, 2, 4, 2, 1, 1, 2]))


In [10]:
# resize
var4 = np.array([1,2,3,4,5,6,7,8,9])
y = np.resize(var4, (3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Flatten
var4 = np.array([1,2,3,4,5,6,7,8,9])
y = np.resize(var4, (3,3))
print(y)
print()
print(y.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]


In [19]:
# Ravel

var4 = np.array([1,2,3,4,5,6,7,8,9])
y = np.resize(var4, (3,3))
print(y)
print()
print(np.ravel(y, order = "F"))
print(np.ravel(y, order = "A"))
print(np.ravel(y, order = "K"))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


Insertion and Deletion in numpy

In [25]:
var = np.array([1,3,4,5,8])
print(var)
v = np.append(var, 2)
print(v)
print(type(v))
v2= np.insert(var,2,10)
print(v2)
v3 = np.insert(var, (2,4), 80)
print(v3)

[1 3 4 5 8]
[1 3 4 5 8 2]
<class 'numpy.ndarray'>
[ 1  3 10  4  5  8]
[ 1  3 80  4  5 80  8]


In [27]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var1)
v1 = np.insert(var1, 2, 10, axis = 0)
print(v1)
v2 = np.insert(var1, 2,[10,45], axis = 1)
print(v2)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]]
[[ 1  2 10  3]
 [ 4  5 45  6]]
